-- =====================================================================
-- EL PARAÍSO — Script único de base de datos (Supabase / PostgreSQL)
-- =====================================================================
-- CÓMO USAR ESTE ARCHIVO (paso a paso, sin conocimientos técnicos):
--
-- 1) Ve a tu proyecto de Supabase → Authentication → Users → Add user.
--    Crea el usuario administrador con el correo y contraseña que tú
--    elijas. Anota el correo exacto que usaste.
--
-- 2) Baja hasta la sección "6) CREAR AL PRIMER ADMINISTRADOR" (al final
--    de este archivo) y reemplaza el texto 'admin@elparaiso.com' por
--    el correo real que usaste en el paso 1.
--
-- 3) Copia TODO este archivo (desde la primera línea hasta la última)
--    y pégalo en Supabase → SQL Editor → New query. Luego presiona "Run".
--
-- Con eso, tu base de datos queda lista. No necesitas tocar nada más
-- aquí dentro; los demás usuarios se crean desde dentro de la aplicación.
-- =====================================================================


-- =====================================================================
-- 1) EXTENSIÓN PARA BÚSQUEDA DE TEXTO (necesaria para buscar clientes)
-- =====================================================================
create extension if not exists pg_trgm;


-- =====================================================================
-- 2) TABLAS
-- =====================================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'client' check (role in ('admin','staff','client')),
  full_name text,
  phone text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  document_number text,
  phone text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists customers_full_name_idx on public.customers using gin (full_name gin_trgm_ops);

create table if not exists public.lockers (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cash_registers (
  id uuid primary key default gen_random_uuid(),
  opened_by uuid references public.profiles(id),
  closed_by uuid references public.profiles(id),
  opening_amount numeric(10,2) not null default 0,
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  status text not null default 'open' check (status in ('open','closed')),
  total_cash numeric(10,2) not null default 0,
  total_qr numeric(10,2) not null default 0,
  total_transfer numeric(10,2) not null default 0,
  total_other_income numeric(10,2) not null default 0,
  total_expenses numeric(10,2) not null default 0,
  closing_balance numeric(10,2) not null default 0,
  notes text
);

create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  sale_number bigint generated by default as identity,
  customer_id uuid references public.customers(id),
  user_id uuid references public.profiles(id),
  cash_register_id uuid references public.cash_registers(id),
  sale_type text not null check (sale_type in ('locker','no_locker')),
  quantity int not null default 1,
  unit_price numeric(10,2) not null,
  subtotal numeric(10,2) not null,
  discount_percentage numeric(5,2) not null default 0,
  discount_amount numeric(10,2) not null default 0,
  total numeric(10,2) not null,
  payment_method text not null check (payment_method in ('cash','qr','transfer')),
  created_at timestamptz not null default now()
);
create unique index if not exists sales_sale_number_uidx on public.sales(sale_number);

create table if not exists public.sale_lockers (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.sales(id) on delete cascade,
  locker_id uuid not null references public.lockers(id),
  released_at timestamptz,
  created_at timestamptz not null default now()
);
-- Un casillero solo puede tener UNA fila "activa" (sin liberar) a la vez.
-- Esto es lo que impide vender el mismo casillero a dos clientes al mismo tiempo.
create unique index if not exists sale_lockers_active_locker_uidx
  on public.sale_lockers(locker_id) where released_at is null;

create table if not exists public.cash_movements (
  id uuid primary key default gen_random_uuid(),
  cash_register_id uuid not null references public.cash_registers(id) on delete cascade,
  type text not null check (type in ('income','expense')),
  concept text not null,
  amount numeric(10,2) not null,
  user_id uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.business_settings (
  id int primary key default 1,
  business_name text not null default 'El Paraíso',
  logo_url text,
  address text,
  phone text,
  email text,
  locker_price numeric(10,2) not null default 20,
  no_locker_price numeric(10,2) not null default 15,
  discount_enabled boolean not null default true,
  discount_default_percentage numeric(5,2) not null default 10,
  updated_at timestamptz not null default now(),
  constraint business_settings_single_row check (id = 1)
);

insert into public.business_settings (id) values (1)
  on conflict (id) do nothing;

-- Casilleros de ejemplo para que la app no se vea vacía la primera vez
-- (puedes borrarlos o desactivarlos luego desde Configuración → Casilleros)
insert into public.lockers (code)
  select 'C-' || lpad(g::text, 2, '0') from generate_series(1, 10) g
  on conflict (code) do nothing;


-- =====================================================================
-- 3) FUNCIÓN AUXILIAR: obtener el rol del usuario que está conectado
-- =====================================================================
create or replace function public.get_my_role()
returns text
language sql
security definer
stable
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;


-- =====================================================================
-- 4) TRIGGER: al registrarse un usuario nuevo, crear su perfil
--    automáticamente con role = 'client'
-- =====================================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, role, full_name)
  values (new.id, 'client', coalesce(new.raw_user_meta_data->>'full_name', new.email))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Trigger de seguridad: un usuario normal no puede cambiarse su propio rol.
-- Solo un administrador puede modificar el rol de cualquier perfil.
create or replace function public.prevent_role_self_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- auth.uid() es NULL cuando el cambio se hace desde el SQL Editor de Supabase
  -- (por ejemplo, al configurar el primer administrador). En ese caso se permite.
  -- Cuando el cambio viene de la aplicación (usuario autenticado), solo un
  -- administrador puede modificar el rol de un perfil.
  if new.role is distinct from old.role and auth.uid() is not null and public.get_my_role() is distinct from 'admin' then
    raise exception 'No tienes permiso para cambiar el rol de este usuario.';
  end if;
  return new;
end;
$$;

drop trigger if exists on_profiles_role_change on public.profiles;
create trigger on_profiles_role_change
  before update on public.profiles
  for each row execute procedure public.prevent_role_self_change();


-- =====================================================================
-- 5) SEGURIDAD: activar RLS (Row Level Security) y definir políticas
-- =====================================================================
alter table public.profiles enable row level security;
alter table public.customers enable row level security;
alter table public.lockers enable row level security;
alter table public.sales enable row level security;
alter table public.sale_lockers enable row level security;
alter table public.cash_registers enable row level security;
alter table public.cash_movements enable row level security;
alter table public.business_settings enable row level security;

-- ---- profiles ----
drop policy if exists "profiles_select" on public.profiles;
create policy "profiles_select" on public.profiles
  for select using (id = auth.uid() or public.get_my_role() = 'admin');

drop policy if exists "profiles_update" on public.profiles;
create policy "profiles_update" on public.profiles
  for update using (id = auth.uid() or public.get_my_role() = 'admin')
  with check (id = auth.uid() or public.get_my_role() = 'admin');

-- ---- business_settings ----
drop policy if exists "business_settings_select" on public.business_settings;
create policy "business_settings_select" on public.business_settings
  for select using (public.get_my_role() in ('admin','staff'));

drop policy if exists "business_settings_update" on public.business_settings;
create policy "business_settings_update" on public.business_settings
  for update using (public.get_my_role() = 'admin')
  with check (public.get_my_role() = 'admin');

-- ---- lockers ----
drop policy if exists "lockers_select" on public.lockers;
create policy "lockers_select" on public.lockers
  for select using (public.get_my_role() in ('admin','staff'));

drop policy if exists "lockers_insert" on public.lockers;
create policy "lockers_insert" on public.lockers
  for insert with check (public.get_my_role() = 'admin');

drop policy if exists "lockers_update" on public.lockers;
create policy "lockers_update" on public.lockers
  for update using (public.get_my_role() = 'admin');

-- ---- customers ----
drop policy if exists "customers_select" on public.customers;
create policy "customers_select" on public.customers
  for select using (public.get_my_role() in ('admin','staff'));

drop policy if exists "customers_insert" on public.customers;
create policy "customers_insert" on public.customers
  for insert with check (public.get_my_role() in ('admin','staff'));

drop policy if exists "customers_update" on public.customers;
create policy "customers_update" on public.customers
  for update using (public.get_my_role() in ('admin','staff'));

-- ---- sales ----
drop policy if exists "sales_select" on public.sales;
create policy "sales_select" on public.sales
  for select using (public.get_my_role() in ('admin','staff'));

drop policy if exists "sales_insert" on public.sales;
create policy "sales_insert" on public.sales
  for insert with check (public.get_my_role() in ('admin','staff'));

-- ---- sale_lockers ----
drop policy if exists "sale_lockers_select" on public.sale_lockers;
create policy "sale_lockers_select" on public.sale_lockers
  for select using (public.get_my_role() in ('admin','staff'));

drop policy if exists "sale_lockers_insert" on public.sale_lockers;
create policy "sale_lockers_insert" on public.sale_lockers
  for insert with check (public.get_my_role() in ('admin','staff'));

drop policy if exists "sale_lockers_update" on public.sale_lockers;
create policy "sale_lockers_update" on public.sale_lockers
  for update using (public.get_my_role() in ('admin','staff'));

-- ---- cash_registers ----
drop policy if exists "cash_registers_select" on public.cash_registers;
create policy "cash_registers_select" on public.cash_registers
  for select using (public.get_my_role() in ('admin','staff'));

drop policy if exists "cash_registers_insert" on public.cash_registers;
create policy "cash_registers_insert" on public.cash_registers
  for insert with check (public.get_my_role() in ('admin','staff'));

drop policy if exists "cash_registers_update" on public.cash_registers;
create policy "cash_registers_update" on public.cash_registers
  for update using (public.get_my_role() in ('admin','staff'));

-- ---- cash_movements ----
drop policy if exists "cash_movements_select" on public.cash_movements;
create policy "cash_movements_select" on public.cash_movements
  for select using (public.get_my_role() in ('admin','staff'));

drop policy if exists "cash_movements_insert" on public.cash_movements;
create policy "cash_movements_insert" on public.cash_movements
  for insert with check (public.get_my_role() in ('admin','staff'));


-- =====================================================================
-- 6) CREAR AL PRIMER ADMINISTRADOR
--    ⬇️  CAMBIA el correo de la línea siguiente por el que usaste al
--    crear el usuario en Authentication → Users → Add user.
-- =====================================================================
do $$
declare
  admin_email text := 'admin@elparaiso.com';  -- <--- CAMBIA ESTE CORREO
  admin_id uuid;
begin
  select id into admin_id from auth.users where email = admin_email;

  if admin_id is null then
    raise notice 'No se encontró ningún usuario con el correo %. Créalo primero en Authentication → Users → Add user, y luego vuelve a ejecutar este bloque.', admin_email;
  else
    insert into public.profiles (id, role, full_name)
    values (admin_id, 'admin', 'Administrador')
    on conflict (id) do update set role = 'admin';
    raise notice 'Usuario % configurado como administrador correctamente.', admin_email;
  end if;
end $$;

-- =====================================================================
-- FIN DEL SCRIPT
-- =====================================================================
